language: python
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
#  - "3.8-dev"  # TODO Remove comment-out when pylint and astroid upgraded to the latest and py2 support dropped

install:
  - pip install tox-travis

script:
  - tox
