jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
    steps:
      - template: ./setup_appium.yml
      - template: ./ios_setup.yml
        parameters:
          xcodeVersion: ${{ parameters.xcodeForIOS }}
      - script: appium driver install xcuitest
        displayName: Install XCUITest driver
      - script: nohup appium --relaxed-security > appium_log.txt &
        condition: ne('${{ parameters.dontRunAppium }}', true)
        displayName: Run Appium in background
      - script: |
          cd test/functional/ios
          python -m pytest ${{ parameters.testFiles}} ${{ parameters.pytestOpt }}
        displayName: Run iOS functional tests
      - template: ./publish_test_result.yml
      - template: ./save_appium_log.yml
        parameters:
          name: ${{ parameters.name }}
