jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: ${{ parameters.ci }}
    steps:
      - template: ./run_appium.yml
      - template: ./ios_setup.yml
        parameters:
          xcodeVersion: ${{ parameters.xcodeForIOS }}
      - script: |
          cd test/functional/ios
          py.test ${{ parameters.testFiles}} ${{ parameters.pytestOpt }}
        displayName: Run iOS functional tests
      - template: ./publish_test_result.yml
