jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - template: ./run_appium.yml
      - script: |
          cd test/functional/${{ parameters.os }}
          py.test ${{ parameters.testFiles}} ${{ parameters.pytestOpt }}
        displayName: Run iOS functional tests
      - template: ./publish_test_result.yml
