jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      ANDROID_SDK_VERSION: ${{ parameters.sdkVer }}
      CI: ${{ parameters.ci }}
    steps:
      - template: ./run_appium.yml
      - script: bash ci-jobs/functional/start-emulator.sh
        displayName: Create and run Emulator
      - script: |
          cd test/functional/android
          py.test ${{ parameters.testFiles}} ${{ parameters.pytestOpt }}
        displayName: Run Android functional tests
      - template: ./publish_test_result.yml
      - template: ./save_appium_log.yml
        parameters:
          name: ${{ parameters.name }}
