jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      ANDROID_SDK_VERSION: ${{ parameters.sdkVer }}
      CI: ${{ parameters.ci }}
    steps:
      - template: ./setup_appium.yml
        parameters:
          DONT_RUN_APPIUM: ${{ parameters.dont_run_appium }}
      - script: appium driver install uiautomator2
        displayName: Install UIAutomator2 driver
      - script: nohup appium --relaxed-security > appium_log.txt &
        condition: ne('${{ parameters.dont_run_appium }}', true)
        displayName: Run Appium in background
      - script: bash ci-jobs/functional/start-emulator.sh
        displayName: Create and run Emulator
      - script: |
          cd test/functional/android
          python -m pytest ${{ parameters.testFiles}} ${{ parameters.pytestOpt }}
        displayName: Run Android functional tests
      - template: ./publish_test_result.yml
      - template: ./save_appium_log.yml
        parameters:
          name: ${{ parameters.name }}
