parameters:
  vmImage: 'macOS-10.15'
  pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'
  androidSdkVer: 30
  xcodeForIOS: 12.3
  CI: true

jobs:
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android6'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'common_tests.py multi_action_tests.py webelement_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
