parameters:
  vmImage: 'macOS-10.15'
  pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'
  androidSdkVer: S
  xcodeForIOS: 12.3
  CI: true

jobs:
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android2'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'ime_tests.py keyboard_tests.py location_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android3'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'appium_service_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
      DONT_RUN_APPIUM: true
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android4'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'finger_print_tests.py screen_record_tests.py settings_tests.py chrome_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
