parameters:
  vmImage: 'macOS-10.14'
  pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'

jobs:
  - template: ./functional/run_ios_test.yml
    parameters:
      name: 'func_test_ios1'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'find_*.py remote_fs_tests.py safari_tests.py'
  - template: ./functional/run_ios_test.yml
    parameters:
      name: 'func_test_ios2'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'applications_tests.py hw_actions_tests.py keyboard_tests.py screen_record_tests.py webdriver_tests.py'
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android1'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'device_time_tests.py find_by_accessibility_id_tests.py find_by_image_tests.py find_by_uiautomator_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android2'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'hw_actions_tests.py ime_tests.py keyboard_tests.py location_tests.py network_connection_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android3'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'activities_tests.py touch_action_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android4'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'finger_print_tests.py screen_record_tests.py settings_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android5'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'applications_tests.py chrome_tests.py context_switching_tests.py remote_fs_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android6'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'webdriver_tests.py'
      sdkVer: 28
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android7'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'multi_action_tests.py'
      sdkVer: 28
