# parameters:
#   vmImage: 'macOS-12'
#   pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'
#   androidSdkVer: 27
#   xcodeForIOS: 13.4
#   CI: true

jobs:
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android4'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'finger_print_tests.py screen_record_tests.py settings_tests.py chrome_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android5'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'context_switching_tests.py remote_fs_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android8'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'network_connection_tests.py log_event_tests.py activities_tests.py hw_actions_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
