parameters:
  vmImage: 'macOS-12'
  pytestOpt: '--doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html'
  androidSdkVer: 27
  xcodeForIOS: 13.4
  CI: true

jobs:
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android5'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'context_switching_tests.py remote_fs_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android6'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'common_tests.py multi_action_tests.py webelement_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android7'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'applications_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
  - template: ./functional/run_android_test.yml
    parameters:
      name: 'func_test_android8'
      vmImage: ${{ parameters.vmImage }}
      pytestOpt: ${{ parameters.pytestOpt }}
      testFiles: 'network_connection_tests.py log_event_tests.py activities_tests.py hw_actions_tests.py'
      sdkVer: ${{ parameters.androidSdkVer }}
      CI: ${{ parameters.ci }}
